### PR TITLE
Bugfix OL + Add HFE & NVC + Add plotting live data script

### PR DESCRIPTION
**Pull request by stache3000**
Bugfix : decimal.overflow hasn't rotate methode
Add HFE & NCV for UT61E-II
Add python script for plotting live data with matplotlib

### CODE REVIEW

**Comment by ljakob** [comment]
cool, thanks for your contribution

**Comment by stache3000** [comment]
Hello, Your project is the first one I found, it works, it's good. I share my little work based on your repo. Do you have more informations about other functions with this USB port, more specifically about write functions, for maintenance operations like calibration?

**Comment by ljakob** [comment]
Hi stache3000,
sorry I don't have any further information. I've needed the code myself because I wanted to characterize a component with a complex series of measurements. I've reverse engineered the USB protocol by capturing the traffic from the windows program and filled the missing peaces by decompiling the bluetooth android app. I've not seen any traces in the apps for calibration but I would guess that all modern  UNI-T products with serial interface share the same protocol (with some variances for value interpretation, see JSON-Files). Since the interface is already there it's a good bet to assume that they use it also for factory calibration - even if the protocol is more like a display/button-thing.
Cheers Leif

**Comment by stache3000** [comment]
Ok, Great Job ! Thanks for your opinion about calibration (I agree)
See U

**Pull request merged**
